version: '3'

services:
  mysql:
    restart: always
    build: docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  phpmyadmin:
    build:
      context: ./docker/phpmyadmin
    restart: on-failure
    ports:
      - 7475:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/phpmyadmin/upload.ini:/usr/local/etc/php/php.ini